version: '3.9'
services:
  mysql:
    image: mysql:5.7
    restart: always
    user: "1000"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: intern
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  app:
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/go-server-exmaple
      - /go/src/go-server-exmaple/tmp
    links:
      - mysql
    depends_on:
      - mysql
volumes:
  mysql:
    driver: local
