version: '3.9'
services:
  mysql:
    image: mysql:5.7
    restart: always
    user: "1000"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: intern
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
